### ISSUE TITLE
[Request] Disable individual brooms

### ISSUE THREAD

**Issue by Vampsku11** [DanManN/BroomSticks#2]
Leaving "item:" unpopulated in the config.yml causes the broom to default to the item originally in the configuration.

For example, this causes broom3 to default to the IRON_SHOVEL when no item is defined:
```
  broom3:
    name: broom3
    speed: 1.0
    durability: 100
    item: 
```

The number of brooms can be artificially limited by setting more than one broom to the same item _and the same speed_. However an option to disable individual brooms would be more apparent for someone wanting to limit the number of tiers.

I have set all five brooms to the same item and same speed and am satisfied with the results.
